name : Quiz API pipeline

on:
#  initiates the pipeline whenever user pushes on the main branch
  pull_request:
    branches:
      - main

# global variable
env:
  DOCKERHUB_USERNAME: darshangautam  
  DOCKERHUB_REPOSITORY: quiz_api  
  IMAGE_VERSION: v1.0.0

jobs:
  # Building the docker image and pushing to the docker registry.
  build_job:
    runs-on: ubuntu-latest # Test is running on ubuntu machine

    steps:
      - name: Clone and checkout to the repository
        uses: actions/checkout@v4 # Clones the repository in the working directory of the runner

      - name: Logging in to the docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Build Node app Image
        run: docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:$IMAGE_VERSION -f Dockerfile  .

      - name: Push Docker Image to Docker Hub
        run: docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:$IMAGE_VERSION

  # Deploying application after test is passed via github runner
  deploy:
    needs: build_job
    runs-on: [self-hosted, linux]  # Deploy will run on your self-hosted runner (EC2)

    steps:
      - name: Run deploy script on EC2
        run: |
          echo "Deploying application..."